import "server-only";
import type { Market } from "@/lib/types";
import {
  CarrierError,
  envSet,
  fetchWithTimeout,
  isPdf,
  normalizePhone,
  postcodeDigits,
  xmlEscape,
  type AdapterContext,
  type CarrierAdapter,
  type CreateShipmentInput,
  type ShipmentRef,
  type TrackingEvent,
} from "./adapter";
import { statusFromText } from "./tracking";
import type { PickupPoint } from "./types";

/**
 * Venipak.
 * Docs: Venipak API (Postman) https://documenter.getpostman.com/view/12497207/TVYCC1o1
 *   and Venipak's official PrestaShop module (API client) https://github.com/mijora/venipak-presta-zendesk (classes/MjvpApi.php)
 *   GET  ws/get_pickup_points?country=LV   public, no credentials (verified 2026-09-25)
 *   POST import/send.php                   form fields user, pass, xml_text (<description type="1"><manifest …><shipment>…)
 *                                          → <answer type="ok"><text>V…E…</text></answer>
 *   POST ws/print_label                    form fields user, pass, pack_no[i], format (a4|other) → PDF
 *   GET  ws/tracking?code=…&type=1&output=csv   public tracking
 * Pack numbers are generated by the sender: "V" + API id + "E" + 7-digit serial; manifest title: API id + yymmdd + 3-digit serial.
 * Env: VENIPAK_USERNAME, VENIPAK_PASSWORD, VENIPAK_API_ID, optional VENIPAK_API_URL (default https://go.venipak.lt/).
 */

const ENV = ["VENIPAK_USERNAME", "VENIPAK_PASSWORD", "VENIPAK_API_ID"];
const BASE = () => (process.env.VENIPAK_API_URL || "https://go.venipak.lt/").replace(/\/?$/, "/");
const PUBLIC_BASE = "https://go.venipak.lt/";

export function venipakConfigured() {
  return envSet(ENV).length === ENV.length;
}

function requireConfig() {
  if (!venipakConfigured()) throw new CarrierError("Venipak API nav konfigurēts (VENIPAK_USERNAME / VENIPAK_PASSWORD / VENIPAK_API_ID).");
}

type RawPoint = {
  id: number | string;
  name?: string;
  display_name?: string;
  code?: string;
  address?: string;
  city?: string;
  zip?: string;
  country?: string;
  lat?: string | number;
  lng?: string | number;
  type?: number;
  size_limit?: number;
  pick_up_enabled?: number;
};

function parseAnswer(xml: string) {
  const ok = /<answer[^>]*type="ok"/i.test(xml);
  const texts = [...xml.matchAll(/<text>([\s\S]*?)<\/text>/gi)].map((m) => m[1].trim()).filter(Boolean);
  return { ok, texts };
}

function yymmdd(d = new Date()) {
  const p = (n: number) => String(n).padStart(2, "0");
  return `${String(d.getFullYear()).slice(2)}${p(d.getMonth() + 1)}${p(d.getDate())}`;
}

export const venipakAdapter: CarrierAdapter = {
  code: "venipak",
  name: "Venipak",
  capabilities() {
    return {
      code: "venipak",
      api: venipakConfigured(),
      envVars: ENV,
      envSet: envSet(ENV),
      pickupPoints: true,
      tracking: true,
      docs: ["https://documenter.getpostman.com/view/12497207/TVYCC1o1", "https://github.com/mijora/venipak-presta-zendesk"],
    };
  },

  async listPickupPoints(country: Market) {
    const res = await fetchWithTimeout(`${PUBLIC_BASE}ws/get_pickup_points?country=${country}`, {
      next: { revalidate: 60 * 60 * 12, tags: ["venipak-points"] },
    });
    if (!res.ok) throw new CarrierError(`Venipak punkti: HTTP ${res.status}`);
    const data = (await res.json()) as RawPoint[];
    return (Array.isArray(data) ? data : [])
      .filter((p) => (p.country ?? country) === country)
      .map((p): PickupPoint => ({
        id: String(p.id),
        name: (p.display_name || p.name || String(p.id)).trim(),
        city: (p.city ?? "").trim(),
        address: [p.address, p.city].filter(Boolean).join(", "),
        postcode: p.zip,
        country,
        lat: p.lat != null && p.lat !== "" ? Number(p.lat) : null,
        lng: p.lng != null && p.lng !== "" ? Number(p.lng) : null,
        meta: { code: p.code ?? null, zip: p.zip ?? null, type: p.type ?? null, size_limit: p.size_limit ?? null, street: p.address ?? null },
      }))
      .sort((a, b) => a.city.localeCompare(b.city, "lv") || a.name.localeCompare(b.name, "lv"));
  },

  async createShipment(input: CreateShipmentInput, ctx: AdapterContext) {
    requireConfig();
    const apiId = String(process.env.VENIPAK_API_ID);
    const r = input.receiver;
    const locker = input.serviceType === "locker";
    const pp = input.pickupPoint;
    if (locker && !pp?.id) throw new CarrierError("Nav norādīts Venipak pakomāts.");

    const day = yymmdd();
    const manifestSerial = await ctx.nextSerial(`venipak-manifest-${day}`);
    const manifestTitle = `${apiId}${day}${String(manifestSerial).padStart(3, "0")}`;
    const packs: string[] = [];
    for (let i = 0; i < input.parcels.length; i++) {
      const serial = await ctx.nextSerial("venipak-pack");
      packs.push(`V${apiId}E${String(serial).padStart(7, "0")}`);
    }

    // For pickup points the consignee is the terminal itself (as in Venipak's own modules).
    const consignee = locker
      ? {
          name: pp!.name ?? "",
          company_code: String(pp!.meta?.code ?? ""),
          country: r.country,
          city: pp!.city ?? "",
          address: String(pp!.meta?.street ?? pp!.address?.split(",")[0] ?? ""),
          post_code: postcodeDigits(String(pp!.meta?.zip ?? pp!.postcode ?? "")),
        }
      : {
          name: r.company || r.name,
          company_code: "",
          country: r.country,
          city: r.city ?? "",
          address: r.street ?? "",
          post_code: postcodeDigits(r.postcode),
        };

    const xml =
      `<?xml version="1.0" encoding="UTF-8"?><description type="1"><manifest title="${xmlEscape(manifestTitle)}" name="${xmlEscape(input.reference)}">` +
      `<shipment><consignee>` +
      `<name>${xmlEscape(consignee.name)}</name>` +
      (consignee.company_code ? `<company_code>${xmlEscape(consignee.company_code)}</company_code>` : "") +
      `<country>${xmlEscape(consignee.country)}</country><city>${xmlEscape(consignee.city)}</city>` +
      `<address>${xmlEscape(consignee.address)}</address><post_code>${xmlEscape(consignee.post_code)}</post_code>` +
      `<contact_person>${xmlEscape(r.name)}</contact_person><contact_tel>${xmlEscape(normalizePhone(r.phone, r.country) ?? "")}</contact_tel>` +
      `<contact_email>${xmlEscape(r.email ?? "")}</contact_email>` +
      `</consignee><attribute>${locker ? "" : "<delivery_type>nwd</delivery_type>"}<comment_text>${xmlEscape(input.reference)}</comment_text></attribute>` +
      input.parcels
        .map((p, i) => {
          const volume = p.l && p.w && p.h ? (p.l * p.w * p.h) / 1_000_000 : 0.01;
          return `<pack><pack_no>${packs[i]}</pack_no><doc_no>${xmlEscape(input.reference)}</doc_no><weight>${Math.max(0.1, Math.round(p.weightKg * 100) / 100)}</weight><volume>${volume.toFixed(3)}</volume></pack>`;
        })
        .join("") +
      `</shipment></manifest></description>`;

    const res = await fetchWithTimeout(`${BASE()}import/send.php`, {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({ user: process.env.VENIPAK_USERNAME!, pass: process.env.VENIPAK_PASSWORD!, xml_text: xml }),
      cache: "no-store",
    });
    const text = await res.text();
    const ans = parseAnswer(text);
    if (!res.ok || !ans.ok) throw new CarrierError(`Venipak atteica sūtījumu: ${ans.texts.join("; ") || text.slice(0, 300) || `HTTP ${res.status}`}`);
    const numbers = ans.texts.filter((t) => /^V\d+E\d+$/.test(t));
    return { trackingNumbers: numbers.length ? numbers : packs, carrierRef: manifestTitle };
  },

  async getLabel(ref: ShipmentRef) {
    requireConfig();
    const params = new URLSearchParams({ user: process.env.VENIPAK_USERNAME!, pass: process.env.VENIPAK_PASSWORD!, format: process.env.VENIPAK_LABEL_FORMAT === "a4" ? "a4" : "other", carrier: "all" });
    ref.trackingNumbers.forEach((n, i) => params.append(`pack_no[${i}]`, n));
    const res = await fetchWithTimeout(`${BASE()}ws/print_label`, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: params, cache: "no-store" });
    const buf = Buffer.from(await res.arrayBuffer());
    if (!res.ok || !isPdf(buf)) throw new CarrierError(`Venipak uzlīme: ${buf.toString("utf8").slice(0, 200) || `HTTP ${res.status}`}`);
    return [buf];
  },

  async track(ref: ShipmentRef) {
    const events: TrackingEvent[] = [];
    for (const code of ref.trackingNumbers.slice(0, 5)) {
      const res = await fetchWithTimeout(`${PUBLIC_BASE}ws/tracking?code=${encodeURIComponent(code)}&type=1&output=csv`, { cache: "no-store" });
      if (!res.ok) throw new CarrierError(`Venipak izsekošana: HTTP ${res.status}`);
      const csv = await res.text();
      // CSV rows (first row = header). Column layout is not formally documented → keep date-like column + remaining text.
      const rows = csv.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
      for (const row of rows.slice(1)) {
        const cols = row.split(/[;,](?=(?:[^"]*"[^"]*")*[^"]*$)/).map((c) => c.replace(/^"|"$/g, "").trim());
        const dateCol = cols.find((c) => /^\d{4}-\d{2}-\d{2}/.test(c));
        const text = cols.filter((c) => c && c !== dateCol && c !== code).join(" · ");
        if (text) events.push({ at: dateCol ? new Date(dateCol.replace(" ", "T")).toISOString() : new Date().toISOString(), text });
      }
    }
    events.sort((a, b) => a.at.localeCompare(b.at));
    const last = events[events.length - 1];
    return { status: last ? statusFromText(last.text) : null, events };
  },
};
